# Generated by Django 5.0 on 2025-12-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_compnaylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('is_offered', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('special_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('special_offer', models.CharField(blank=True, max_length=255, null=True)),
                ('serving_count', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='Application.productmodel')),
            ],
        ),
    ]
