# Generated by Django 5.0 on 2025-12-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_productweightmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercartitemsmodel',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Application.productweightmodel'),
        ),
        migrations.AddField(
            model_name='userorderitemsmodel',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Application.productweightmodel'),
        ),
    ]
