# Generated by Django 5.0 on 2025-11-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_aboutussectionimages_carouselimage_contactbanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussectionimages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutussectionimages',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactbanner',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='steptellsstory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='steptellsstory',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
