# Generated by Django 5.0 on 2025-12-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_usercartitemsmodel_weight_userorderitemsmodel_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='weight',
        ),
    ]
