# Generated by Django 5.0 on 2025-12-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_remove_productmodel_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='serving_count',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='special_offer',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='special_tags',
        ),
    ]
