# Generated by Django 5.0 on 2025-11-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_aboutussectionimages_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='customer_reviews/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
