# Generated by Django 5.0 on 2025-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_remove_productmodel_offer_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercartitemsmodel',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='userorderitemsmodel',
            name='weight',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='serving_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='special_offer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='special_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductWeightModel',
        ),
    ]
