# Generated by Django 5.0 on 2025-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_aboutuscustomerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussectionimages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutussectionimages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
