# Generated by Django 5.0 on 2025-12-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_shippingcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordermodel',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.useraddressmodel'),
        ),
    ]
