# Generated by Django 5.0 on 2025-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_recipemodel_recipestepmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
