# Generated by Django 5.0 on 2025-12-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_conatactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conatactmodel',
            old_name='created_at',
            new_name='created',
        ),
    ]
