# Generated by Django 5.0 on 2025-12-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_rename_created_at_conatactmodel_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConatactModel',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
