# Generated by Django 5.0 on 2025-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_usercartitemsmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
