# Generated by Django 5.0 on 2025-12-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_delete_conatactmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
