# Generated by Django 5.0 on 2025-11-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_recipemodel_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestepmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
