# Generated by Django 5.0 on 2025-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_remove_recipestepmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
