# Generated by Django 5.0 on 2025-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_alter_contactmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='display_name',
            new_name='display_name1',
        ),
        migrations.AddField(
            model_name='category',
            name='display_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
