# Generated by Django 5.0 on 2025-12-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_rename_display_name_category_display_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderitemsmodel',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
