# Generated by Django 5.0 on 2025-12-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_useraddressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
