# Generated by Django 5.0 on 2025-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_userorderitemsmodel_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordermodel',
            name='shipping_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
