# Generated by Django 5.0 on 2025-12-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_useraddressmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorderitemsmodel',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='userorderitemsmodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='userorderitemsmodel',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='userorderitemsmodel',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='userorderitemsmodel',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='final_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Application.useraddressmodel'),
        ),
        migrations.AddField(
            model_name='userordermodel',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userorderitemsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Application.productmodel'),
        ),
        migrations.AlterField(
            model_name='userorderitemsmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
