# Generated by Django 5.0 on 2025-12-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_userordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='video_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
