# Generated by Django 5.0 on 2025-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_thumbnail_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordermodel',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
