# Generated by Django 5.0 on 2025-12-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_userordermodel_invoice'),
        ('Application', '0020_userordermodel_invoice'),
    ]

    operations = [
    ]
