# Generated by Django 5.0 on 2025-12-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0019_thumbnail_video_url'),
        ('Application', '0021_merge_20251203_1703'),
    ]

    operations = [
    ]
