# Generated by Django 5.0 on 2025-12-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_category_display_name_category_image'),
        ('Application', '0022_merge_20251205_0846'),
    ]

    operations = [
    ]
