"""
Django settings for SpeedineProject project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from datetime import timedelta


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ls^m7e^n9*rm*9n8-r$9)bvj+vcplib^w13kf7=c1^%-d=bd&r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['13.127.218.52','*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Application',
    'corsheaders',
    'nested_admin',
    
]
AUTH_USER_MODEL = 'Application.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SpeedineProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SpeedineProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')



# Add this to settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field




CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Methods',
    'Access-Control-Allow-Headers',
]
CORS_EXPOSE_HEADERS = [
    'Content-Disposition',
    'Content-Length',
    'Content-Type',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Methods',
    'Access-Control-Allow-Headers',
    
]   
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',  
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'Application.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 10,
}


SIMPLE_JWT = {
    # --- Token Lifetimes (Best Practice) ---
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),     # short-lived
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),        # 1 week (standard)
    "ROTATE_REFRESH_TOKENS": True,                      # auto rotate refresh token for security
    "BLACKLIST_AFTER_ROTATION": True,                   # blacklist old refresh

    # --- Algorithms / Keys ---
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,

    # --- Authorization Header (rarely used since we use cookies) ---
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),

    # --- Claims ---
    "TOKEN_TYPE_CLAIM": "token_type",

    # --- Cookie Based Auth (IMPORTANT) ---
    "AUTH_COOKIE": "access_token",            # Name of access token cookie
    "AUTH_COOKIE_REFRESH": "refresh_token",   # Name of refresh token cookie

    "AUTH_COOKIE_SECURE": True,               # Only HTTPS (production)
    "AUTH_COOKIE_HTTP_ONLY": True,            # Cannot be accessed via JS
    "AUTH_COOKIE_SAMESITE": "None",           # Allows cross-site frontend/backend

    "AUTH_COOKIE_PATH": "/",                  # Cookie available anywhere
    "AUTH_COOKIE_DOMAIN": None,               # Use your domain in production if needed

    # --- Extra Options ---
    "AUTH_COOKIE_REFRESH_PATH": "/api/auth/refresh/",  # Endpoint for refresh (optional)
}



AUTHENTICATION_BACKENDS = [
    "Application.backends.UsernameEmailPhoneBackend",  # ✅ our custom backend
    "django.contrib.auth.backends.ModelBackend",    # keep default for admin
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'speedine.in@gmail.com'
EMAIL_HOST_PASSWORD = 'iuvtqgazggjyqmvt'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


GEOIP_PATH = os.path.join(BASE_DIR, "geoip")  # Place GeoLite2-City.mmdb here


# --------------------------------------------------
# Jazzmin setup
# --------------------------------------------------

JAZZMIN_SETTINGS = {
    "site_title": "Speedine Admin",
    "site_header": "Speedine Admin",
    "site_brand": "Speedine Admin",
    "welcome_sign": "Welcome to Speedine Admin",
    'site_logo': 'images/speedine.png',
    "site_logo_classes": "img-circle",
    "site_icon": "images/speedine.png",
    "login_logo": 'images/speedine2.png',
    "login_logo_classes": "",
    "copyright": "Speedine",
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-secondary navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": False
}


# --------------------------------------------------
# Redis Setup 
# --------------------------------------------------

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        }
    }
}



REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0



# --------------------------------------------------
# Firebase Push Notification setup
# --------------------------------------------------



RAZORPAY_KEY_ID = "rzp_test_RmcyuTUo7jtgxV"
RAZORPAY_KEY_SECRET = "AcR520eZv6RMFm5OwEBHtA2j"